### ISSUE TITLE
ZZZ checkin not working

### ISSUE THREAD

**Issue by Emeeya** [ashytuna/HoYoLABDailyCheckin#1]
Hey, I noticed for a while now the ZZZ automatic checkin has not been working, still works with Genshin and HSR though. Tried removing and reinstalling the addon but still having the issue.

**Comment by nganhtu** [comment]
Fixed with commit [7cb46d5](https://github.com/nganhtu/HoYoLABDailyCheckin/commit/7cb46d5c7592534e990c9e0137c4faaa4df35303).
Thank you for your report.
